No npm release

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -81,19 +81,19 @@ jobs:
         cp ../target/wasm/cdd-java.js ./dist/cdd-java.js
         cp ../target/wasm/cdd-java.wasm ./dist/cdd-java.wasm
 
-    - name: Publish NPM Package
-      run: |
-        cd package
-        # Update version based on tag
-        VERSION=${GITHUB_REF#refs/tags/}
-        VERSION=${VERSION#v}
-        # If tag is 'latest', maybe we don't want to fail npm version. We could skip it or handle it.
-        if [ "$VERSION" != "latest" ]; then
-          npm version $VERSION --no-git-tag-version
-        fi
-        npm publish --access public || echo "Publishing skipped or failed"
-      env:
-        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+#    - name: Publish NPM Package
+#      run: |
+#        cd package
+#        # Update version based on tag
+#        VERSION=${GITHUB_REF#refs/tags/}
+#        VERSION=${VERSION#v}
+#        # If tag is 'latest', maybe we don't want to fail npm version. We could skip it or handle it.
+#        if [ "$VERSION" != "latest" ]; then
+#          npm version $VERSION --no-git-tag-version
+#        fi
+#        npm publish --access public || echo "Publishing skipped or failed"
+#      env:
+#        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
     - name: Rename and Checksum
       run: |
